workers_dev = true

name = "hatch-discordbot"
main = "./dist/server.js"
compatibility_date = "2022-12-14"

no_bundle = true
minify = false

[placement]
mode = "smart"

#route = { zone_name="klartnet.ml", pattern="hatch-bot.discord.klartnet.ml", custom_domain=true }



[build]
command = "npm run build:publish"


[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true # Required by Slshx