workers_dev = false
name = "sayhi-bot"
main = "./dist/server.mjs"
compatibility_date = "2022-12-14"
routes = [
	{ zone_name="klartnet.ml", pattern="sayhi.discord.klartnet.ml", custom_domain=true }
]

[build]
command = "node --no-warnings ./scripts/build.js publish"


[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true # Required by Slshx