workers_dev = false

name = "hatch-bot"
main = "./dist/server.mjs"
compatibility_date = "2022-12-14"

no_bundle = true
minify = false

route = { zone_name="klartnet.ml", pattern="hatch-bot.discord.klartnet.ml", custom_domain=true }



[build]
command = "node --no-warnings ./scripts/build.js publish"


[miniflare]
global_async_io = true # Required by Slshx